api {
    web_server: http://localhost:9091
    api_server: http://localhost:9092
    files_server: http://localhost:9093
    credentials {
    "access_key"="Y3UR48LJNL08MZKZGPBJ55PW693SMY"
    "secret_key"="aIQMAxeljNYFjLY9UUnXg12HhAfzNMElI3MrMvZ19y66_QLfywCOlEwjjH5y-Doqofk"
    }
}
